import pandas as pd

df = pd.read_csv(r"C:\Users\salma\OneDrive\Desktop\my video games project\data\games.csv")

previous_game = {
    'Age of Empires II': 'Age of Empires',
    'Age of Empires III': 'Age of Empires II',
    'Age of Empires IV': 'Age of Empires III',
    'Age of Empires IX': 'Age of Empires VIII',
    'Age of Empires V': 'Age of Empires IV',
    'Age of Empires VI': 'Age of Empires V',
    'Age of Empires VII': 'Age of Empires VI',
    'Age of Empires VIII': 'Age of Empires VII',
    'Age of Empires X': 'Age of Empires IX',
    'Age of Empires XI': 'Age of Empires X',
    'Age of Empires XII': 'Age of Empires XI',
    'Age of Empires XVI': 'Age of Empires XV',
    "Baldur's Gate 2": "Baldur's Gate 1",
    "Baldur's Gate 3": "Baldur's Gate 2",
    "Baldur's Gate 4": "Baldur's Gate 3",
    "Baldur's Gate 5": "Baldur's Gate 4",
    "Baldur's Gate 6": "Baldur's Gate 5",
    'Black Alert 2': 'Black Alert 1',
    'Black Alert 3': 'Black Alert 2',
    'Black Alert 4': 'Black Alert 3',
    'Black Alert 5': 'Black Alert 4',
    'Black Alert 6': 'Black Alert 5',
    'Black Desert 2': 'Black Desert 1',
    'Black Desert 3': 'Black Desert 2',
    'Blue Alert 2': 'Blue Alert 1',
    'Blue Alert 3': 'Blue Alert 2',
    'Blue Alert 4': 'Blue Alert 3',
    'Blue Alert 5': 'Blue Alert 4',
    'Blue Alert 6': 'Blue Alert 5',
    'Civilization II': 'Civilization',
    'Civilization III': 'Civilization II',
    'Civilization IV': 'Civilization III',
    'Civilization IX': 'Civilization VIII',
    'Civilization V': 'Civilization IV',
    'Civilization VI': 'Civilization V',
    'Civilization VII': 'Civilization VI',
    'Civilization VIII': 'Civilization VII',
    'Civilization X': 'Civilization IX',
    'Civilization XI': 'Civilization X',
    'Civilization XII': 'Civilization XI',
    'Civilization XVI': 'Civilization XV',
    'Company of Heroes 2': 'Company of Heroes 1',
    'Company of Heroes 3': 'Company of Heroes 2',
    'Company of Heroes 4': 'Company of Heroes 3',
    'Company of Heroes 5': 'Company of Heroes 4',
    'Company of Heroes 6': 'Company of Heroes 5',
    'Counter-Strike 2': 'Counter-Strike',
    'Counter-Strike 3': 'Counter-Strike 2',
    'Crusader Kings II': 'Crusader Kings',
    'Crusader Kings III': 'Crusader Kings II',
    'Crusader Kings IV': 'Crusader Kings III',
    'Crusader Kings IX': 'Crusader Kings VIII',
    'Crusader Kings V': 'Crusader Kings IV',
    'Crusader Kings VI': 'Crusader Kings V',
    'Crusader Kings VII': 'Crusader Kings VI',
    'Crusader Kings VIII': 'Crusader Kings VII',
    'Crusader Kings X': 'Crusader Kings IX',
    'Crusader Kings XI': 'Crusader Kings X',
    'Crusader Kings XII': 'Crusader Kings XI',
    'Crusader Kings XVI': 'Crusader Kings XV',
    'Dark Souls 2': 'Dark Souls 1',
    'Dark Souls 3': 'Dark Souls 2',
    'Dark Souls 4': 'Dark Souls 3',
    'Dark Souls 5': 'Dark Souls 4',
    'Dark Souls 6': 'Dark Souls 5',
    'Dead Space 2': 'Dead Space 1',
    'Dead Space 3': 'Dead Space 2',
    'Dead Space 4': 'Dead Space 3',
    'Dead Space 5': 'Dead Space 4',
    'Dead Space 6': 'Dead Space 5',
    'Dirt 2': 'Dirt 1',
    'Dirt 3': 'Dirt 2',
    'Dirt 4': 'Dirt 3',
    'Dirt 5': 'Dirt 4',
    'Dirt 6': 'Dirt 5',
    'Doom 2': 'Doom 1',
    'Doom 3': 'Doom 2',
    'Dragon Ball FighterZ 2': 'Dragon Ball FighterZ 1',
    'Dragon Ball FighterZ 3': 'Dragon Ball FighterZ 2',
    'Dragon Quest II': 'Dragon Quest',
    'Dragon Quest III': 'Dragon Quest II',
    'Dragon Quest IV': 'Dragon Quest III',
    'Dragon Quest IX': 'Dragon Quest VIII',
    'Dragon Quest V': 'Dragon Quest IV',
    'Dragon Quest VI': 'Dragon Quest V',
    'Dragon Quest VII': 'Dragon Quest VI',
    'Dragon Quest VIII': 'Dragon Quest VII',
    'Dragon Quest X': 'Dragon Quest IX',
    'Dragon Quest XI': 'Dragon Quest X',
    'Dragon Quest XII': 'Dragon Quest XI',
    'Dragon Quest XVI': 'Dragon Quest XV',
    'Euro Truck Simulator 2': 'Euro Truck Simulator',
    'Euro Truck Simulator 3': 'Euro Truck Simulator 2',
    'Euro Truck Simulator 4': 'Euro Truck Simulator 3',
    'Euro Truck Simulator 5': 'Euro Truck Simulator 4',
    'Euro Truck Simulator 6': 'Euro Truck Simulator 5',
    'Europa Universalis II': 'Europa Universalis',
    'Europa Universalis III': 'Europa Universalis II',
    'Europa Universalis IV': 'Europa Universalis III',
    'Europa Universalis IX': 'Europa Universalis VIII',
    'Europa Universalis V': 'Europa Universalis IV',
    'Europa Universalis VI': 'Europa Universalis V',
    'Europa Universalis VII': 'Europa Universalis VI',
    'Europa Universalis VIII': 'Europa Universalis VII',
    'Europa Universalis X': 'Europa Universalis IX',
    'Europa Universalis XI': 'Europa Universalis X',
    'Europa Universalis XII': 'Europa Universalis XI',
    'Europa Universalis XVI': 'Europa Universalis XV',
    'F-Zero 2': 'F-Zero 1',
    'F-Zero 3': 'F-Zero 2',
    'F1 2023': 'F1 2022',
    'F1 2024': 'F1 2023',
    'F1 2025': 'F1 2024',
    'F1 2026': 'F1 2025',
    'FIFA 2023': 'FIFA 2022',
    'FIFA 2024': 'FIFA 2023',
    'FIFA 2025': 'FIFA 2024',
    'FIFA 2026': 'FIFA 2025',
    'Fall Guys 2': 'Fall Guys 1',
    'Fall Guys 3': 'Fall Guys 2',
    'Farming Simulator 2023': 'Farming Simulator 2022',
    'Farming Simulator 2024': 'Farming Simulator 2023',
    'Farming Simulator 2025': 'Farming Simulator 2024',
    'Farming Simulator 2026': 'Farming Simulator 2025',
    'Final Fantasy II': 'Final Fantasy',
    'Final Fantasy III': 'Final Fantasy II',
    'Final Fantasy IV': 'Final Fantasy III',
    'Final Fantasy IX': 'Final Fantasy VIII',
    'Final Fantasy V': 'Final Fantasy IV',
    'Final Fantasy VI': 'Final Fantasy V',
    'Final Fantasy VII': 'Final Fantasy VI',
    'Final Fantasy VIII': 'Final Fantasy VII',
    'Final Fantasy X': 'Final Fantasy IX',
    'Final Fantasy XI': 'Final Fantasy X',
    'Final Fantasy XII': 'Final Fantasy XI',
    'Final Fantasy XVI': 'Final Fantasy XV',
    'Firewatch 2': 'Firewatch',
    'Firewatch 3': 'Firewatch 2',
    'Fortnite 2': 'Fortnite',
    'Fortnite 3': 'Fortnite 2',
    'Forza Motorsport 2': 'Forza Motorsport 1',
    'Forza Motorsport 3': 'Forza Motorsport 2',
    'Forza Motorsport 4': 'Forza Motorsport 3',
    'Forza Motorsport 5': 'Forza Motorsport 4',
    'Forza Motorsport 6': 'Forza Motorsport 5',
    "Garry's Mod 2": "Garry's Mod 1",
    "Garry's Mod 3": "Garry's Mod 2",
    'Goat Simulator 2': 'Goat Simulator 1',
    'Goat Simulator 3': 'Goat Simulator 2',
    'Goat Simulator 4': 'Goat Simulator 3',
    'Goat Simulator 5': 'Goat Simulator 4',
    'Goat Simulator 6': 'Goat Simulator 5',
    'Gold Alert 2': 'Gold Alert 1',
    'Gold Alert 3': 'Gold Alert 2',
    'Gold Alert 4': 'Gold Alert 3',
    'Gold Alert 5': 'Gold Alert 4',
    'Gold Alert 6': 'Gold Alert 5',
    'Gone Home 2': 'Gone Home',
    'Gone Home 3': 'Gone Home 2',
    'Gran Turismo 2': 'Gran Turismo 1',
    'Gran Turismo 3': 'Gran Turismo 2',
    'Gran Turismo 4': 'Gran Turismo 3',
    'Gran Turismo 5': 'Gran Turismo 4',
    'Gran Turismo 6': 'Gran Turismo 5',
    'Green Alert 2': 'Green Alert 1',
    'Green Alert 3': 'Green Alert 2',
    'Green Alert 4': 'Green Alert 3',
    'Green Alert 5': 'Green Alert 4',
    'Green Alert 6': 'Green Alert 5',
    'Guild Wars 2': 'Guild Wars',
    'Guild Wars 3': 'Guild Wars 2',
    'Guild Wars 4': 'Guild Wars 3',
    'Guild Wars 5': 'Guild Wars 4',
    'Guild Wars 6': 'Guild Wars 5',
    'Guilty Gear 2': 'Guilty Gear 1',
    'Guilty Gear 3': 'Guilty Gear 2',
    'Halo 2': 'Halo: Combat Evolved',
    'Halo 3': 'Halo 2',
    'Hyper Scape 2': 'Hyper Scape 1',
    'Hyper Scape 3': 'Hyper Scape 2',
    'Injustice 2': 'Injustice 1',
    'Injustice 3': 'Injustice 2',
    'Injustice 4': 'Injustice 3',
    'Injustice 5': 'Injustice 4',
    'Injustice 6': 'Injustice 5',
    'King of Fighters 2023': 'King of Fighters 2022',
    'King of Fighters 2024': 'King of Fighters 2023',
    'King of Fighters 2025': 'King of Fighters 2024',
    'King of Fighters 2026': 'King of Fighters 2025',
    'Life is Strange 2': 'Life is Strange',
    'Life is Strange 3': 'Life is Strange 2',
    'Lost Ark 2': 'Lost Ark 1',
    'Lost Ark 3': 'Lost Ark 2',
    'MLB The Show 2023': 'MLB The Show 2022',
    'MLB The Show 2024': 'MLB The Show 2023',
    'MLB The Show 2025': 'MLB The Show 2024',
    'MLB The Show 2026': 'MLB The Show 2025',
    'Madden NFL 2023': 'Madden NFL 2022',
    'Madden NFL 2024': 'Madden NFL 2023',
    'Madden NFL 2025': 'Madden NFL 2024',
    'Madden NFL 2026': 'Madden NFL 2025',
    'Mario Kart 2': 'Mario Kart 1',
    'Mario Kart 3': 'Mario Kart 2',
    'Mario Kart 4': 'Mario Kart 3',
    'Mario Kart 5': 'Mario Kart 4',
    'Mario Kart 6': 'Mario Kart 5',
    'Mega Man II': 'Mega Man',
    'Mega Man III': 'Mega Man II',
    'Mega Man IV': 'Mega Man III',
    'Mega Man IX': 'Mega Man VIII',
    'Mega Man V': 'Mega Man IV',
    'Mega Man VI': 'Mega Man V',
    'Mega Man VII': 'Mega Man VI',
    'Mega Man VIII': 'Mega Man VII',
    'Mega Man X': 'Mega Man IX',
    'Mega Man XI': 'Mega Man X',
    'Mega Man XII': 'Mega Man XI',
    'Mega Man XVI': 'Mega Man XV',
    'Microsoft Flight Simulator 2023': 'Microsoft Flight Simulator 2022',
    'Microsoft Flight Simulator 2024': 'Microsoft Flight Simulator 2023',
    'Microsoft Flight Simulator 2025': 'Microsoft Flight Simulator 2024',
    'Microsoft Flight Simulator 2026': 'Microsoft Flight Simulator 2025',
    'Minecraft 2': 'Minecraft',
    'Minecraft 3': 'Minecraft 2',
    'Monument Valley 2': 'Monument Valley 1',
    'Monument Valley 3': 'Monument Valley 2',
    'Monument Valley 4': 'Monument Valley 3',
    'Monument Valley 5': 'Monument Valley 4',
    'Monument Valley 6': 'Monument Valley 5',
    'Mortal Kombat II': 'Mortal Kombat',
    'Mortal Kombat III': 'Mortal Kombat II',
    'Mortal Kombat IV': 'Mortal Kombat III',
    'Mortal Kombat IX': 'Mortal Kombat VIII',
    'Mortal Kombat V': 'Mortal Kombat IV',
    'Mortal Kombat VI': 'Mortal Kombat V',
    'Mortal Kombat VII': 'Mortal Kombat VI',
    'Mortal Kombat VIII': 'Mortal Kombat VII',
    'Mortal Kombat X': 'Mortal Kombat IX',
    'Mortal Kombat XI': 'Mortal Kombat X',
    'Mortal Kombat XII': 'Mortal Kombat XI',
    'Mortal Kombat XVI': 'Mortal Kombat XV',
    'Myst 2': 'Myst 1',
    'Myst 3': 'Myst 2',
    'NBA 2023': 'NBA 2022',
    'NBA 2024': 'NBA 2023',
    'NBA 2025': 'NBA 2024',
    'NBA 2026': 'NBA 2025',
    'NHL 2023': 'NHL 2022',
    'NHL 2024': 'NHL 2023',
    'NHL 2025': 'NHL 2024',
    'NHL 2026': 'NHL 2025',
    "No Man's Sky 2": "No Man's Sky 1",
    "No Man's Sky 3": "No Man's Sky 2",
    'Outlast 2': 'Outlast',
    'Outlast 3': 'Outlast 2',
    'Outlast 4': 'Outlast 3',
    'Outlast 5': 'Outlast 4',
    'Outlast 6': 'Outlast 5',
    'Overwatch 2': 'Overwatch',
    'Overwatch 3': 'Overwatch 2',
    'Overwatch 4': 'Overwatch 3',
    'Overwatch 5': 'Overwatch 4',
    'Overwatch 6': 'Overwatch 5',
    'Oxenfree 2': 'Oxenfree',
    'Oxenfree 3': 'Oxenfree 2',
    'PGA Tour 2023': 'PGA Tour 2022',
    'PGA Tour 2024': 'PGA Tour 2023',
    'PGA Tour 2025': 'PGA Tour 2024',
    'PGA Tour 2026': 'PGA Tour 2025',
    'Persona 2': 'Persona 1',
    'Persona 3': 'Persona 2',
    'Persona 4': 'Persona 3',
    'Persona 5': 'Persona 4',
    'Persona 6': 'Persona 5',
    'Portal 2': 'Portal',
    'Portal 3': 'Portal 2',
    'Portal 4': 'Portal 3',
    'Portal 5': 'Portal 4',
    'Portal 6': 'Portal 5',
    'Red Alert 2': 'Red Alert 1',
    'Red Alert 3': 'Red Alert 2',
    'Red Alert 4': 'Red Alert 3',
    'Red Alert 5': 'Red Alert 4',
    'Red Alert 6': 'Red Alert 5',
    'Resident Evil 2': 'Resident Evil',
    'Resident Evil 3': 'Resident Evil 2',
    'Resident Evil 4': 'Resident Evil 3',
    'Resident Evil 5': 'Resident Evil 4',
    'Resident Evil 6': 'Resident Evil 5',
    'Ridge Racer 2': 'Ridge Racer 1',
    'Ridge Racer 3': 'Ridge Racer 2',
    'Ridge Racer 4': 'Ridge Racer 3',
    'Ridge Racer 5': 'Ridge Racer 4',
    'Ridge Racer 6': 'Ridge Racer 5',
    'Roblox 2': 'Roblox',
    'Roblox 3': 'Roblox 2',
    'Silent Hill 2': 'Silent Hill 1',
    'Silent Hill 3': 'Silent Hill 2',
    'Silent Hill 4': 'Silent Hill 3',
    'Silent Hill 5': 'Silent Hill 4',
    'Silent Hill 6': 'Silent Hill 5',
    'Soma 2': 'Soma 1',
    'Soma 3': 'Soma 2',
    'Sonic the Hedgehog 2': 'Sonic the Hedgehog 1',
    'Sonic the Hedgehog 3': 'Sonic the Hedgehog 2',
    'Sonic the Hedgehog 4': 'Sonic the Hedgehog 3',
    'Sonic the Hedgehog 5': 'Sonic the Hedgehog 4',
    'Sonic the Hedgehog 6': 'Sonic the Hedgehog 5',
    'SoulCalibur II': 'SoulCalibur',
    'SoulCalibur III': 'SoulCalibur II',
    'SoulCalibur IV': 'SoulCalibur III',
    'SoulCalibur IX': 'SoulCalibur VIII',
    'SoulCalibur V': 'SoulCalibur IV',
    'SoulCalibur VI': 'SoulCalibur V',
    'SoulCalibur VII': 'SoulCalibur VI',
    'SoulCalibur VIII': 'SoulCalibur VII',
    'SoulCalibur X': 'SoulCalibur IX',
    'SoulCalibur XI': 'SoulCalibur X',
    'SoulCalibur XII': 'SoulCalibur XI',
    'SoulCalibur XVI': 'SoulCalibur XV',
    'StarCraft 2': 'StarCraft 1',
    'StarCraft 3': 'StarCraft 2',
    'StarCraft 4': 'StarCraft 3',
    'StarCraft 5': 'StarCraft 4',
    'StarCraft 6': 'StarCraft 5',
    'Street Fighter II': 'Street Fighter',
    'Street Fighter III': 'Street Fighter II',
    'Street Fighter IV': 'Street Fighter III',
    'Street Fighter IX': 'Street Fighter VIII',
    'Street Fighter V': 'Street Fighter IV',
    'Street Fighter VI': 'Street Fighter V',
    'Street Fighter VII': 'Street Fighter VI',
    'Street Fighter VIII': 'Street Fighter VII',
    'Street Fighter X': 'Street Fighter IX',
    'Street Fighter XI': 'Street Fighter X',
    'Street Fighter XII': 'Street Fighter XI',
    'Street Fighter XVI': 'Street Fighter XV',
    'Super People 2': 'Super People 1',
    'Super People 3': 'Super People 2',
    'Tekken 2': 'Tekken 1',
    'Tekken 3': 'Tekken 2',
    'Tekken 4': 'Tekken 3',
    'Tekken 5': 'Tekken 4',
    'Tekken 6': 'Tekken 5',
    'Terraria 2': 'Terraria',
    'Terraria 3': 'Terraria 2',
    'Tetris 2': 'Tetris 1',
    'Tetris 3': 'Tetris 2',
    'The Sims 2': 'The Sims',
    'The Sims 3': 'The Sims 2',
    'The Sims 4': 'The Sims 3',
    'The Sims 5': 'The Sims 4',
    'The Sims 6': 'The Sims 5',
    'Titanfall 2': 'Titanfall',
    'Titanfall 3': 'Titanfall 2',
    'Titanfall 4': 'Titanfall 3',
    'Titanfall 5': 'Titanfall 4',
    'Titanfall 6': 'Titanfall 5',
    'UFC 2': 'UFC 1',
    'UFC 3': 'UFC 2',
    'UFC 4': 'UFC 3',
    'UFC 5': 'UFC 4',
    'UFC 6': 'UFC 5',
    'Until Dawn 2': 'Until Dawn 1',
    'Until Dawn 3': 'Until Dawn 2',
    'Valheim 2': 'Valheim',
    'Valheim 3': 'Valheim 2',
    'Valorant 2': 'Valorant',
    'Valorant 3': 'Valorant 2',
    'WWE 2023': 'WWE 2022',
    'WWE 2024': 'WWE 2023',
    'WWE 2025': 'WWE 2024',
    'WWE 2026': 'WWE 2025',
    'Warzone 2': 'Warzone',
    'Warzone 3': 'Warzone 2',
    'Warzone 4': 'Warzone 3',
    'Warzone 5': 'Warzone 4',
    'Warzone 6': 'Warzone 5',
    'White Alert 2': 'White Alert 1',
    'White Alert 3': 'White Alert 2',
    'White Alert 4': 'White Alert 3',
    'White Alert 5': 'White Alert 4',
    'White Alert 6': 'White Alert 5',
    'Wipeout 2': 'Wipeout 1',
    'Wipeout 3': 'Wipeout 2',
    'XCOM 2': 'XCOM 1',
    'XCOM 3': 'XCOM 2',
    'XCOM 4': 'XCOM 3',
    'XCOM 5': 'XCOM 4',
    'XCOM 6': 'XCOM 5',
    'eFootball 2023': 'eFootball 2022',
    'eFootball 2024': 'eFootball 2023',
    'eFootball 2025': 'eFootball 2024',
    'eFootball 2026': 'eFootball 2025',
}
df["previous_game"] = df["title"].map(previous_game)
df.columns

df.to_csv("new_games")