/*
What is the total and average revenue generated by games
 that have no extra monetization features (pure premium) versus games that use DLC,
  microtransactions, or loot boxes?*/


SELECT 
    CASE 
        WHEN dlc_released = 0 AND microtransactions = 0 AND loot_boxes = 0 THEN 'No Monetization'
        ELSE 'Monetized'
    END AS game_type,
    ROUND(SUM(global_sales_million), 2) AS total_sales,
    ROUND(AVG(global_sales_million), 2) AS average_sales
FROM games

group by game_type 

/*

Which specific monetization feature (or combination of features) yields the highest average revenue per title? */


SELECT 
    CASE 
        WHEN dlc_released = 0 AND microtransactions = 0 AND loot_boxes = 0 THEN 'Pure Premium (No Monetization)'
        WHEN dlc_released = 1 AND microtransactions = 0 AND loot_boxes = 0 THEN 'Expansion Model (DLC Only)'
        WHEN dlc_released = 0 AND microtransactions = 1 AND loot_boxes = 0 THEN 'Microtransactions Only'
        WHEN dlc_released = 0 AND microtransactions = 0 AND loot_boxes = 1 THEN 'Loot Boxes Only'
        WHEN dlc_released = 1 AND microtransactions = 1 AND loot_boxes = 0 THEN 'Hybrid Premium (DLC + MTX)'
        WHEN dlc_released = 1 AND microtransactions = 0 AND loot_boxes = 1 THEN 'Hybrid Premium (DLC + Loot Boxes)'
        WHEN dlc_released = 0 AND microtransactions = 1 AND loot_boxes = 1 THEN 'Live Service / F2P Core (MTX + Loot Boxes)'
        WHEN dlc_released = 1 AND microtransactions = 1 AND loot_boxes = 1 THEN 'Full Monetization (DLC + MTX + Loot Boxes)'
        ELSE 'Other'
    END AS monetization_strategy,
    COUNT(*) AS total_titles,
    ROUND(SUM(estimated_revenue_million_usd ), 2) AS total_revenue_million,
    ROUND(AVG(estimated_revenue_million_usd ), 2) AS avg_revenue_per_title,
    ROUND(AVG(global_sales_million), 2) AS avg_units_sold_million
FROM games
GROUP BY 
  monetization_strategy
ORDER BY 
    avg_revenue_per_title DESC;

/*
How much revenue do live-service elements (microtransactions/loot boxes) generate compared to traditional expansion packs (DLC)? */
SELECT 
    CASE 
        WHEN dlc_released = 0 AND microtransactions = 0 AND loot_boxes = 0 THEN 'Pure Premium (No Monetization)'
        WHEN dlc_released = 1 AND microtransactions = 0 AND loot_boxes = 0 THEN 'Traditional DLC Model (Expansions Only)'
        WHEN dlc_released = 0 AND (microtransactions = 1 OR loot_boxes = 1) THEN 'Pure Live-Service Model (MTX/Loot Boxes Only)'
        WHEN dlc_released = 1 AND (microtransactions = 1 OR loot_boxes = 1) THEN 'Hybrid Model (DLC + Live-Service Double-Dip)'
        ELSE 'Other'
    END AS business_model,
    COUNT(*) AS total_titles,
    ROUND(SUM(estimated_revenue_million_usd ), 2) AS total_revenue_million,
    ROUND(AVG(estimated_revenue_million_usd ), 2) AS avg_revenue_per_title,
    ROUND(AVG(global_sales_million), 2) AS avg_units_sold_million
FROM games
GROUP BY business_model
ORDER BY total_revenue_million DESC;


/*
 What is the average Metacritic score (critic sentiment) versus user score (player sentiment) for games
  with microtransactions and loot boxes compared to those without?
 */


SELECT 
    CASE 
        WHEN dlc_released = 0 AND microtransactions = 0 AND loot_boxes = 0 THEN 'No Monetization'
        ELSE 'Monetized'
    END AS game_type,
    ROUND(AVG(metacritic_score), 2) AS Metacritic_score,
    ROUND(AVG(user_score*10), 2) AS user_score
FROM games

group by game_type 


/*
 The Sentiment Delta: What is the average gap between critic scores and user scores when predatory monetization
  (loot boxes/microtransactions) is present? 
  Does intense monetization cause games to get "review-bombed" by users even if critics like them?
 */
SELECT 
    CASE 
        WHEN dlc_released = 0 AND microtransactions = 0 AND loot_boxes = 0 THEN 'No Monetization'
        when dlc_released = 1 AND microtransactions = 1 AND loot_boxes = 1 THEN 'Intense Monetization'
        else "medium Monetization"
    END AS game_type,
    ROUND(AVG(metacritic_score), 2) AS Metacritic_score,
    ROUND(AVG(user_score*10), 2) AS user_score ,
    ROUND(AVG(metacritic_score) - AVG(user_score * 10), 2) AS sentiment_delta
FROM games

group by game_type 

/*
 Is there a statistical difference in review counts? 
 Do monetized games provoke a higher volume of user reviews (indicating a highly passionate or angry player base)?
 */

SELECT 
    CASE 
        WHEN dlc_released = 0 AND microtransactions = 0 AND loot_boxes = 0 THEN 'No Monetization'
        ELSE 'Monetized'
    END AS game_type,
    COUNT(*) AS total_games_in_bucket,
    ROUND(AVG(critic_review_count), 2) AS avg_critic_reviews_per_title,
    ROUND(AVG(user_review_count), 2) AS avg_user_reviews_per_title
FROM games
GROUP BY game_type;


/*
 What is the average revenue and global sales volume of games available on Game Pass versus traditional purchase-only titles?
 */
#

SELECT 
CASE 
        WHEN game_pass = 1 THEN 'Game Pass Title'
        ELSE 'Purchase-Only Title'
    END AS distribution_model,
    ROUND(AVG(estimated_revenue_million_usd ), 2) AS average_revenue,
    ROUND(AVG(global_sales_million ), 2) AS global_sales
FROM games
GROUP BY game_type;

