/*
What is the total and average revenue generated by games
 that have no extra monetization features (pure premium) versus games that use DLC,
  microtransactions, or loot boxes?*/


SELECT 
    CASE 
        WHEN dlc_released = 0 AND microtransactions = 0 AND loot_boxes = 0 THEN 'No Monetization'
        ELSE 'Monetized'
    END AS game_type,
    ROUND(SUM(global_sales_million), 2) AS total_sales,
    ROUND(AVG(global_sales_million), 2) AS average_sales
FROM games

group by game_type 

/*

Which specific monetization feature (or combination of features) yields the highest average revenue per title? */


SELECT 
    CASE 
        WHEN dlc_released = 0 AND microtransactions = 0 AND loot_boxes = 0 THEN 'Pure Premium (No Monetization)'
        WHEN dlc_released = 1 AND microtransactions = 0 AND loot_boxes = 0 THEN 'Expansion Model (DLC Only)'
        WHEN dlc_released = 0 AND microtransactions = 1 AND loot_boxes = 0 THEN 'Microtransactions Only'
        WHEN dlc_released = 0 AND microtransactions = 0 AND loot_boxes = 1 THEN 'Loot Boxes Only'
        WHEN dlc_released = 1 AND microtransactions = 1 AND loot_boxes = 0 THEN 'Hybrid Premium (DLC + MTX)'
        WHEN dlc_released = 1 AND microtransactions = 0 AND loot_boxes = 1 THEN 'Hybrid Premium (DLC + Loot Boxes)'
        WHEN dlc_released = 0 AND microtransactions = 1 AND loot_boxes = 1 THEN 'Live Service / F2P Core (MTX + Loot Boxes)'
        WHEN dlc_released = 1 AND microtransactions = 1 AND loot_boxes = 1 THEN 'Full Monetization (DLC + MTX + Loot Boxes)'
        ELSE 'Other'
    END AS monetization_strategy,
    COUNT(*) AS total_titles,
    ROUND(SUM(estimated_revenue_million_usd ), 2) AS total_revenue_million,
    ROUND(AVG(estimated_revenue_million_usd ), 2) AS avg_revenue_per_title,
    ROUND(AVG(global_sales_million), 2) AS avg_units_sold_million
FROM games
GROUP BY 
  monetization_strategy
ORDER BY 
    avg_revenue_per_title DESC;

/*
How much revenue do live-service elements (microtransactions/loot boxes) generate compared to traditional expansion packs (DLC)? */
SELECT 
    CASE 
        WHEN dlc_released = 0 AND microtransactions = 0 AND loot_boxes = 0 THEN 'Pure Premium (No Monetization)'
        WHEN dlc_released = 1 AND microtransactions = 0 AND loot_boxes = 0 THEN 'Traditional DLC Model (Expansions Only)'
        WHEN dlc_released = 0 AND (microtransactions = 1 OR loot_boxes = 1) THEN 'Pure Live-Service Model (MTX/Loot Boxes Only)'
        WHEN dlc_released = 1 AND (microtransactions = 1 OR loot_boxes = 1) THEN 'Hybrid Model (DLC + Live-Service Double-Dip)'
        ELSE 'Other'
    END AS business_model,
    COUNT(*) AS total_titles,
    ROUND(SUM(estimated_revenue_million_usd ), 2) AS total_revenue_million,
    ROUND(AVG(estimated_revenue_million_usd ), 2) AS avg_revenue_per_title,
    ROUND(AVG(global_sales_million), 2) AS avg_units_sold_million
FROM games
GROUP BY business_model
ORDER BY total_revenue_million DESC;



